# Generated by Django 5.0.3 on 2024-03-30 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('achievement_id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mountains',
            fields=[
                ('mountain_id', models.UUIDField(primary_key=True, serialize=False)),
                ('mountain_name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('image_path', models.CharField(max_length=256)),
                ('image_source', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.UUIDField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.UUIDField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('root_comment_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serverapp.comments')),
                ('mountain_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serverapp.mountains')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serverapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='Users_Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serverapp.achievements')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serverapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='Users_Mountains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mountain_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serverapp.mountains')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serverapp.users')),
            ],
        ),
    ]
